spin_manifest_version = 2

[application]
name = "{{project-name}}"
version = "0.2.0"
authors = ["{{authors}}"]
description = ""

[[trigger.http]]
route = "/..."
component = "{{project-name}}"

[component.{{project-name | kebab_case}}]
source = "target/wasm32-wasi/release/{{crate_name}}.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]

[component.{{project-name | kebab_case}}.build]
command = "cargo leptos build --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/pkg/..."
component = "pkg"

[component.pkg]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "target/site/pkg", destination = "/" }]
